---
- name: Configure Interfaces on Cisco IOS & IOS-XR
  hosts: all
  gather_facts: false
  vars_files:
    - "src_cfg/{{ fcfg }}.yml"
  tasks:
    - name: "Generating config files for interfaces"
      template:
        src: templates/gen_xr_int.j2
        dest: "gen_configs/{{ inventory_hostname }}_int.txt"
      tags: 
        - gen_int

    - name: "Generating config files for VRFs"
      template:
        src: templates/gen_vrfs.j2
        dest: "gen_configs/{{ inventory_hostname }}_vrfs.txt"
      tags: 
        - gen_vrfs

    - name: "Generating config files for OSPFs"
      template:
        src: templates/gen_ospf1.j2
        dest: "gen_configs/{{ inventory_hostname }}_ospf.txt"
      tags: 
        - gen_ospf
        
#### Configure interfaces 
    - name: "Run configuration interfaces"
      include_tasks: "devices/{{ ansible_network_os }}/interfaces.yml"
      args:
        apply:
          tags:
            - conf_int
      tags:
        - conf_int

#### UP Interfaces
    - name: "UP interfaces"
      include_tasks: "devices/{{ ansible_network_os }}/up_int.yml"
      args:
        apply:
          tags:
            - up_int
      tags:
        - up_int

####  Configure VRFs
    - name: "Run configuration VRFs"
      include_tasks: "devices/{{ ansible_network_os }}/vrfs.yml"
      args:
        apply:
          tags:
            - conf_vrfs
      tags:
        - conf_vrfs

#### Configure OSPF 
    - name: "Run configuration OSPF"
      include_tasks: "devices/{{ ansible_network_os }}/OSPF.yml"
      args:
        apply:
          tags:
            - conf_ospf
      tags:
        - conf_ospf

#### Ping main interfaces
    - name: Ping addresses for checking
      ios_ping:
        dest: "{{ item }}"
      loop: "{{ ping_check_base[inventory_hostname] }}"
      tags: 
        - ping_int

#### Ping loopback interfaces
    - name: Ping Loopback addresses for checking
      ios_ping:
        dest: "{{ item }}"
      loop: "{{ ping_check_loop[inventory_hostname] }}"
      tags: 
        - ping_loop

#### Gather IOS facts
    - name: Gather ios_facts
      ios_facts:
      register: version
      tags:
      - gen_facts_ios

    - name: View IOS Facts
      debug:
        msg: "CSR Version - {{version.ansible_facts.ansible_net_version}}"
      tags:
      - gen_facts_ios
