all:
  children:
    csr1000v:
      hosts:
        R1:
          ansible_host: 10.121.1.61
        R2:
          ansible_host: 10.121.1.62
        R3:
          ansible_host: 10.121.1.63
        R4:
          ansible_host: 10.121.1.64
        R5:
          ansible_host: 10.121.1.65
        R6:
          ansible_host: 10.121.1.66
      vars:
        ansible_user: root
        ansible_ssh_pass: cisco
        ansible_network_os: ios
    # switch:
    #   hosts:
    #     sw1:
    #       ansible_host: 10.121.1.90
    #     sw2:
    #       ansible_host: 10.121.1.91
    xrv:
      hosts:
        XR1:
          ansible_host: 10.121.1.81
        XR2:
          ansible_host: 10.121.1.82
      vars:
        ansible_user: cisco
        ansible_ssh_pass: cisco
        ansible_network_os: iosxr

  vars:
    ansible_connection: network_cli



